---
all:
  hosts:
    server1:
      ansible_host: ubuntu.orb.local@orb
      ansible_user: ubuntu
    server2:
      ansible_host: ubuntu2.orb.local@orb
      ansible_user: ubuntu2
    server3:
      ansible_host: docker1.orb.local@orb
      ansible_user: docker1
    server4:
      ansible_host: docker2.orb.local@orb
      ansible_user: docker2
  children:
    ubuntu_hosts:
      hosts:
        server1:
        server2:
    docker_hosts:
      hosts:
        server3:
        server4: